runtime: python27
api_version: 1
threadsafe: true
handlers:
  - url: /
    static_files: dist/angular-mat-table-reordering/index.html
    upload: dist/angular-mat-table-reordering/index.html

  - url: /
    static_dir: dist/angular-mat-table-reordering/
skip_files:
  - e2e/
  - node_modules/
  - src/
  - coverage
  - ^(./)?\..$
  - ^(./)?.\.json$
  - ^(./)?.\.md$
  - ^(./)?.\.yaml$
  - ^LICENSE
